apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GreekgodRequiredLabels
metadata:
  name: namespace-label
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    # labels: ["state"] # REQUIRED: Every namespace must have this label
